package example.androidgridlayoutactivity;


import com.j256.ormlite.field.DatabaseField;
import com.orm.dsl.Collection;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class SimpleData {

	// id is generated by the database and set on the object auto-magically
	@DatabaseField(generatedId = true)
	int id;
	@DatabaseField(index = true)
	String fileName;
	@DatabaseField
	String type;
	@DatabaseField
	String color;
	@DatabaseField
	String explain;
	@DatabaseField
	Collection matches;

	SimpleData() {
		// needed by ormlite
	}

public SimpleData(int id, String fileName, String type, String color, String explain, Collection matches) {
	this.id = id;
	this.fileName = fileName;
	this.type = type;
	this.color = color;
	this.explain = explain;
	this.matches = matches;
}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("file name =").append(fileName);
		sb.append(", ").append("type =").append(type);
		sb.append(", ").append("color =").append(color);
		sb.append(", ").append("explanation =").append(explain);
		sb.append(", ").append("List of matches =").append(matches.toString());
		return sb.toString();
	}
}
